package migration

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"

	"github.com/fatih/color"

	"github.com/apsdsm/joka/cmd/shared"
	"github.com/apsdsm/joka/internal/domains/migration/app"
	"github.com/apsdsm/joka/internal/domains/migration/domain"
	"github.com/apsdsm/joka/internal/domains/migration/infra"
)

// RunConsolidateCommand handles "migrate consolidate --up-to <index>". It
// replaces every migration file with a single baseline produced by pg_dump, and
// reconciles joka's tracking tables to match.
//
// Joka does not generate schema DDL. The dump tool is the reference
// implementation; joka's job here is bookkeeping — write the file, remove the
// records the file no longer covers, delete the files it replaced.
//
// The target must be the most recently applied migration. A dump describes the
// database as it is now, not as it was at some earlier migration, so
// consolidating "up to" an older index would write a baseline that does not match
// the index it carries.
type RunConsolidateCommand struct {
	DB            *sql.DB
	DSN           string
	MigrationsDir string
	UpToIndex     string
	AutoConfirm   bool
	OutputFormat  string
}

// Execute performs the consolidation.
func (r RunConsolidateCommand) Execute(ctx context.Context) error {
	jsonOut := r.OutputFormat == shared.OutputJSON

	fail := func(err error) error {
		if jsonOut {
			return shared.PrintErrorJSON(err)
		}
		color.Red("Error: %v", err)
		return err
	}

	adapter := infra.NewPostgresDBAdapter(r.DB)

	// 0. Refuse drivers joka cannot dump, before touching anything.
	dumper := infra.NewSchemaDumper(r.DB, r.DSN)

	// 1. Build the migration chain.
	chain, chainErr := app.GetMigrationChainAction{
		DB:            adapter,
		MigrationsDir: r.MigrationsDir,
	}.Execute(ctx)
	if chainErr != nil {
		return fail(chainErr)
	}

	// 2. Locate the target and check it is the last applied migration.
	targetIdx := -1
	for i, m := range chain {
		if m.MigrationIndex == r.UpToIndex {
			targetIdx = i
			break
		}
	}
	if targetIdx < 0 {
		return fail(fmt.Errorf("migration %s not found in chain", r.UpToIndex))
	}

	lastApplied := -1
	for i, m := range chain {
		if m.Status == domain.StatusApplied {
			lastApplied = i
		}
	}
	if targetIdx != lastApplied {
		if lastApplied < 0 {
			return fail(fmt.Errorf("no migrations are applied — nothing to consolidate"))
		}
		return fail(fmt.Errorf("%w: --up-to must name the last applied migration (%s), not %s\n\nThe baseline is produced by dumping the live schema, which reflects every applied migration. Consolidating up to an earlier index would write a file that does not match the index it carries",
			domain.ErrNotLastApplied, chain[lastApplied].MigrationIndex, r.UpToIndex))
	}

	// Must have at least 2 migrations to consolidate.
	if targetIdx < 1 {
		return fail(fmt.Errorf("need at least 2 migrations to consolidate (found %d)", targetIdx+1))
	}

	// 3. Dump the schema. Nothing has been written or deleted yet, so a missing
	// binary or a version mismatch aborts harmlessly.
	dumped, err := dumper.Dump(ctx)
	if err != nil {
		return fail(err)
	}

	newFileName := fmt.Sprintf("%s_consolidated.sql", r.UpToIndex)
	newFilePath := filepath.Join(r.MigrationsDir, newFileName)
	baseline := fmt.Sprintf(
		"-- Consolidated migration\n-- Generated by joka migrate consolidate using %s\n-- Replaces every migration up to and including %s\n\n%s",
		dumper.Tool(), r.UpToIndex, dumped)

	// 4. Show what will happen and confirm.
	filesToDelete := chain[:targetIdx+1]

	// The target migration keeps its record — the new file carries its index.
	// Everything before it is replaced and must leave the tracking tables, or the
	// chain (zipped positionally against files) breaks on the next command.
	var recordsToRemove []string
	for _, m := range chain[:targetIdx] {
		recordsToRemove = append(recordsToRemove, m.MigrationIndex)
	}

	if !jsonOut {
		color.Green("Consolidation plan:")
		fmt.Printf("  Target: %s\n", r.UpToIndex)
		fmt.Printf("  Schema dumped with: %s\n", dumper.Tool())
		fmt.Printf("  Migrations to consolidate: %d\n", len(filesToDelete))
		for _, m := range filesToDelete {
			fmt.Printf("    - %s_%s.sql\n", m.MigrationIndex, m.FileName)
		}
		fmt.Printf("  New file: %s (%d lines)\n", newFileName, countLines(baseline))
		fmt.Printf("  Migration records to remove: %d\n", len(recordsToRemove))
		fmt.Println()
	}

	if !r.AutoConfirm && !jsonOut {
		if !shared.Confirm("Proceed with consolidation? This will delete the original migration files. (only 'yes' will proceed): ") {
			fmt.Println("Consolidation aborted by user.")
			return shared.ErrCancelled
		}
	}

	// 5. Write the baseline.
	if err := os.WriteFile(newFilePath, []byte(baseline), 0644); err != nil {
		return fail(fmt.Errorf("writing consolidated file: %w", err))
	}

	// 6. Reconcile the tracking tables. Done before deleting files so a failure
	// here leaves the migrations directory intact and the database unchanged.
	if err := adapter.RemoveMigrationRecords(ctx, recordsToRemove); err != nil {
		os.Remove(newFilePath) //nolint:errcheck — best-effort rollback of step 5
		return fail(fmt.Errorf("reconciling migration records: %w", err))
	}

	// 7. Delete the migration files the baseline replaces.
	var deleted []string
	for _, m := range filesToDelete {
		// The target file may already be the consolidated file we just wrote.
		if m.FileFullPath == newFilePath {
			deleted = append(deleted, m.MigrationIndex)
			continue
		}
		if err := os.Remove(m.FileFullPath); err != nil {
			return fail(fmt.Errorf("deleting %s: %w — records were already reconciled; remove the remaining consolidated files by hand", m.FileFullPath, err))
		}
		deleted = append(deleted, m.MigrationIndex)
	}

	// 8. Report on the resulting migration directory.
	remaining, err := infra.ListMigrationFiles(r.MigrationsDir)
	if err != nil {
		if jsonOut {
			return shared.PrintErrorJSON(err)
		}
		color.Red("Warning: could not verify migration directory: %v", err)
		return nil
	}

	if jsonOut {
		shared.PrintJSON(map[string]any{
			"status":          "ok",
			"consolidated":    deleted,
			"new_file":        newFileName,
			"total_files":     len(remaining),
			"records_removed": recordsToRemove,
			"dump_tool":       dumper.Tool(),
		})
		return nil
	}

	color.Green("Consolidation complete.")
	fmt.Printf("  Created: %s\n", newFileName)
	fmt.Printf("  Deleted: %d migration files\n", len(deleted))
	fmt.Printf("  Removed: %d migration records\n", len(recordsToRemove))
	fmt.Printf("  Remaining migration files: %d\n", len(remaining))
	return nil
}

// countLines reports how many lines a script occupies, for the plan output.
func countLines(script string) int {
	count := 0
	for _, c := range script {
		if c == '\n' {
			count++
		}
	}
	return count
}
