package app

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// fkRefPattern matches REFERENCES followed by a table name, optionally quoted
// with backticks (MySQL) or double quotes (PostgreSQL).
var fkRefPattern = regexp.MustCompile(`(?i)REFERENCES\s+[` + "`" + `"]*(\w+)[` + "`" + `"]*`)

// ParseFKDependencies extracts foreign key dependencies from a snapshot schema
// map. Returns a map where each key is a table name and its value is the list
// of distinct tables it depends on (referenced via FOREIGN KEY ... REFERENCES).
// Self-references and references to tables outside the schema are ignored.
func ParseFKDependencies(schema map[string]string) map[string][]string {
	deps := make(map[string][]string)
	for table := range schema {
		deps[table] = nil
	}

	for table, ddl := range schema {
		seen := make(map[string]bool)
		matches := fkRefPattern.FindAllStringSubmatch(ddl, -1)
		for _, m := range matches {
			ref := m[1]
			if ref == table || seen[ref] {
				continue
			}
			if _, inSchema := schema[ref]; !inSchema {
				continue
			}
			seen[ref] = true
			deps[table] = append(deps[table], ref)
		}
		sort.Strings(deps[table])
	}

	return deps
}

// TopologicalSort returns table names ordered so that dependencies come before
// dependents. Uses Kahn's algorithm. Returns an error if a cycle is detected.
// When multiple tables are eligible at the same level, they are sorted
// alphabetically for deterministic output.
func TopologicalSort(deps map[string][]string) ([]string, error) {
	// Build reverse adjacency: for each table, which tables depend on it.
	dependents := make(map[string][]string)
	inDegree := make(map[string]int)

	for table := range deps {
		inDegree[table] = 0
		if dependents[table] == nil {
			dependents[table] = nil
		}
	}

	for table, depList := range deps {
		seen := make(map[string]bool)
		for _, dep := range depList {
			if seen[dep] {
				continue
			}
			seen[dep] = true
			inDegree[table]++
			dependents[dep] = append(dependents[dep], table)
		}
	}

	// Seed with zero-dependency tables.
	var queue []string
	for table, deg := range inDegree {
		if deg == 0 {
			queue = append(queue, table)
		}
	}
	sort.Strings(queue)

	var result []string
	for len(queue) > 0 {
		table := queue[0]
		queue = queue[1:]
		result = append(result, table)

		for _, dependent := range dependents[table] {
			inDegree[dependent]--
			if inDegree[dependent] == 0 {
				queue = append(queue, dependent)
			}
		}
		sort.Strings(queue)
	}

	if len(result) != len(inDegree) {
		return nil, fmt.Errorf("circular dependency detected among tables")
	}

	return result, nil
}

// autoIncPattern matches MySQL AUTO_INCREMENT=N table options so they can be
// stripped from consolidated output (the exact counter value is meaningless for
// a fresh schema).
var autoIncPattern = regexp.MustCompile(`\s*AUTO_INCREMENT=\d+`)

// GenerateConsolidatedSQL builds a single SQL string from a schema map with
// tables ordered according to the provided order slice. MySQL AUTO_INCREMENT
// counter values are stripped since they are not meaningful for fresh schemas.
func GenerateConsolidatedSQL(schema map[string]string, order []string) string {
	var parts []string
	for _, table := range order {
		ddl := strings.TrimSpace(schema[table])
		ddl = autoIncPattern.ReplaceAllString(ddl, "")
		if !strings.HasSuffix(ddl, ";") {
			ddl += ";"
		}
		parts = append(parts, ddl)
	}
	header := "-- Consolidated migration\n-- Generated by joka migrate consolidate\n"
	return header + "\n" + strings.Join(parts, "\n\n") + "\n"
}
